import { Metadata } from 'next';
import { Cormorant_Garamond } from 'next/font/google';
import './globals.css';

const cormorant = Cormorant_Garamond({
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Gym Helper',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${cormorant.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
